name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: test
        run: make test_coverage
      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage.txt
          verbose: true
